import React from 'react';
import { useNavigate } from 'react-router-dom';

function AdminReports() {
    const navigate = useNavigate();
    const styles = {
        pageContainer: {
            fontFamily: 'system-ui, sans-serif',
            margin: '20px',
            padding: '24px',
            backgroundColor: '#f8fafc',
            borderRadius: '16px',
            border: '1px solid #e2e8f0'
        },
        heading: {
            color: '#0f172a',
            marginBottom: '20px',
            fontSize: '1.5rem'
        },
        grid: {
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
            gap: '16px'
        },
        card: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            textAlign: 'center',
            backgroundColor: '#ffffff',
            border: '1px solid #e2e8f0',
            borderRadius: '12px',
            padding: '20px',
            boxShadow: '0px 4px 6px -1px rgba(0,0,0,0.02)',
            transition: 'all 0.2s'
        },
        emojiIcon: {
            fontSize: '50px',
            borderRadius: '50%',
            objectFit: 'cover',
            border: '1px solid #cbd5e1'
        },
        info: {
            margin: '9px auto'
        },
        title: {
            fontSize: '1.1rem',
            fontWeight: '600',
            color: '#1e293b',
            margin: 0
        },
        text: {
            fontSize: '0.9rem',
            color: '#64748b',
            margin: '4px 0'
        },
        button: {
            width: '100%',
            backgroundColor: '#2563eb',
            color: '#ffffff',
            border: 'none',
            borderRadius: '8px',
            margin: '9px auto',
            padding: '10px 16px',
            fontWeight: '600',
            cursor: 'pointer',
            boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
            transition: 'background-color 0.2s'
        }
    };

    const reportsList = [
        { id: 'R01', image: '💰', title: 'Financial Sales Report', category: 'Finance', date: '2026-07-27', generatedBy: 'Aanya Sharma', status: 'Completed' },
        { id: 'R02', image: '🚀', title: 'User Growth & Analytics', category: 'Analytics', date: '2026-07-26', generatedBy: 'Rohan Verma', status: 'Pending' },
        { id: 'R03', image: '📦', title: 'Inventory & Operations Log', category: 'Operations', date: '2026-07-25', generatedBy: 'Priya Patel', status: 'Completed' },
        { id: 'R04', image: '🛡️', title: 'System Security Audit', category: 'Security', date: '2026-07-24', generatedBy: 'Arjun Nair', status: 'Failed' },
        { id: 'R05', image: '🤝', title: 'Customer Feedback Summary', category: 'Support', date: '2026-07-23', generatedBy: 'Sneha Reddy', status: 'Completed' }
    ];

    return (
        <div style={styles.pageContainer}>
            <h2 style={styles.heading}>System Reports</h2>
            <div style={styles.grid}>
                {reportsList.map((r) => (
                    <div key={r.id} style={styles.card}>
                        <div>
                            <span src={r.image} alt={r.title} style={styles.image} />
                            <span style={styles.emojiIcon}>{r.image}</span>
                            <div style={styles.info}>
                                <h4 style={styles.title}>{r.title}</h4>
                                <p style={styles.text}><strong>Category:</strong> {r.category}</p>
                                <p style={styles.text}><strong>Generated By:</strong> {r.generatedBy}</p>
                                <p style={styles.text}><strong>Date:</strong> <span style={{ color: '#2563eb', fontWeight: 'bold' }}>{r.date}</span></p>
                            </div>
                        </div>
                        <button
                            style={styles.button}
                            onClick={() => alert(`Downloading report: ${r.title}`)}
                        >
                            Download Report
                        </button>
                    </div>
                ))}
            </div>
        </div>
    );
}

export default AdminReports;